[[redirects]]
from = "/*"
to = "http://178.128.7.239/wp-json/wp/v2/pages?_embed="
status = 200
force = true
[[redirects]]
from = "/*"
to = "http://178.128.7.239/wp-json/wp/v2/posts?_embed="
status = 200
force = true
[[redirects]]
from = "/*"
to = "http://api.asianclassics.org/nlm/_all/:splat"
status = 200
force = true
[[redirects]]
from = "/api/*"
to = "http://endpoint.com/api/:splat"
status = 200
force = true